 - name: Install essential packages
   check_mode: no
   ansible.builtin.apt:
     name:
       - nginx
       - ca-certificates
       - curl
       - gnupg
       - htop
       - build-essential
       - libssl-dev
     state: present
   become: yes
